# docker-compose.yml
# Start the container(s): docker compose -f docker-compose.yml --project-name fakeapi up -d
# Stop the container(s): docker compose rm -f -s fakeapi redis
version: "3.9"
networks:
   backend:
      name: backend
services:
  fakeapi:
    image: fakeapi:2.0
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=redis.lab
      - REDIS_PORT=6379
      - FAKEAPI_INTF=0.0.0.0
      - FAKEAPI_PORT=8000
      - FAKEAPI_SERVER_KEY=server-key.pem
      - FAKEAPI_SERVER_CRT=server-crt.pem
    container_name: server1
    hostname: server1
    domainname: backend.com
    networks:
      backend:

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
    container_name: redis.lab
    hostname: redis.lab
    domainname: backend.com
    networks:
       backend:
