# filename: fakeapi.yml
# docker compose -f fakeapi.yml --project-name fakeapi up -d
networks:
   backend:
      name: backend

services:
  fakeapi1:
    image: fakeapi
    volumes:
      - type: bind
        source: $PWD/src
        target: /usr/src/data
        read_only: true
    ports:
      - "9443:9443"
    restart: unless-stopped
    environment:
      - FAKEAPI_ENV=/usr/src/data/.env
    container_name: server1
    hostname: server1
    domainname: backend.com
    networks:
      backend:
        ipv4_address: 172.31.11.11
