# fakeapi.yml
# Start the container: docker compose -f fakeapi.yml --project-name fakeapi up -d
# Stop the container: docker container rm -f server1
networks:
   backend:
      name: backend

services:
  fakeapi1:
    image: fakeapi
    volumes:
      - type: bind
        source: $PWD
        target: /usr/src/data
        # read_only: true
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DATABASE=/usr/src/data/data.json
    container_name: server1
    hostname: server1
    domainname: backend.com
    networks:
      backend:
        ipv4_address: 172.31.11.11
